name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
